version: 2
jobs:
  build:
    branches:
      only:
        - master
    machine:
      enabled: true
      image: circleci/classic:201711-01
    steps:
      - run:
          name: install git-lfs
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install -y git-lfs
            git lfs install
      - checkout
      - run:
          name: Start ssh-agent
          command: |
            ssh-agent -s > ~/.ssh_agent_conf
            source ~/.ssh_agent_conf
            for _k in $(ls ${HOME}/.ssh/id_*); do
              ssh-add ${_k} || true
            done
      - run:
          name: execute build job
          command: |
            BRANCH_NAME=$(date "+%Y%m%d%H%M%S")
            CI_REMOTE_REPOSITORY="git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git"
            IMGNAME="Ubuntu_armhf_nopkg"
            IMGFILE="${IMGNAME}.img"
            cat "${IMGNAME}.?" > "${IMGFILE}"
            rm Ubuntu_armhf_nopkg.?
            echo "unpack image ${IMGFILE}"
            ls -l "${IMGFILE}"
            LODEV=$(sudo losetup -f)
            sudo losetup "${LODEV}" "${IMGFILE}"
            sudo mount "${LODEV}" /mnt
            touch /mnt/${BRANCH_NAME}"
            sudo umount /mnt
            sudo losetup -d "${LODEV}"
            sh split.sh
            echo "create new branch ${BRANCH_NAME}"
            ls -la
            git checkout -b "${BRANCH_NAME}"
            git add .
            git status
            echo "push to server"
            git config --global user.email "nagamatu@gmail.com"
            git config --global user.name "Tatsuo Nagamatsu"
            git commit -m "[auto] branch (${BRANCH_NAME}) [ci skip]"
            git push "${CI_REMOTE_REPOSITORY}" "${BRANCH_NAME}"
      - run:
          name: Print the Current Time
          command: date
