version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: build container
          command: docker build -t nagamatu/loopback .
      - run:
          name: run container
          command: docker run --env __USERNAME=${__USERNAME} --env __PASSWORD=${__PASSWORD} --privileged -t nagamatu/loopback
      - run:
          name: Print the Current Time
          command: date
