version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: check ssh
          command: ls ~/.ssh
      - run:
          name: Start ssh-agent
          command: |
            ssh-agent -s > ~/.ssh_agent_conf
            source ~/.ssh_agent_conf
            for _k in $(ls ${HOME}/.ssh/id_*); do
              ssh-add ${_k} || true
            done
      - run:
          name: build container
          command: docker build --build-arg ssh_key="$(cat ~/.ssh/id_rsa)" --build-arg -t nagamatu/loopback .
      - run:
          name: run container
          command: docker run --env CIRCLE_PROJECT_USERNAME=${CIRCLE_PROJECT_USERNAME} --env CI_PROJECT_REPONAME=${CI_PROJECT_REPONAME} --privileged -t nagamatu/loopback
      - run:
          name: Print the Current Time
          command: date
